"""remove_unit_concept

Revision ID: 2f13dd899cd5
Revises: 14aa0e4e624e
Create Date: 2026-07-11 01:14:57.544900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2f13dd899cd5'
down_revision: Union[str, None] = '14aa0e4e624e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('property_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_leases_properties', 'properties', ['property_id'], ['id'])
        batch_op.drop_column('unit_id')
    op.drop_table('units')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_id', sa.INTEGER(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_leases_units', 'units', ['unit_id'], ['id'])
        batch_op.drop_column('property_id')
    op.create_table('units',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('property_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
